# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sergejs Sušinskis
# See LICENSE file in the repository root for full license text.
# Generated by the ccode-to-codex mirror sync on 2026-04-14 from input revision 9a2403fb.

import contextlib
import importlib.util
import io
import json
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path
from unittest.mock import patch


SCRIPT_PATH = (
    Path(__file__).resolve().parents[1] / "scripts" / "migrate_claude_workflows_to_codex.py"
)
SPEC = importlib.util.spec_from_file_location("migrate_claude_workflows_to_codex", SCRIPT_PATH)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
sys.modules[SPEC.name] = MODULE
SPEC.loader.exec_module(MODULE)

PRIMITIVES_PATH = Path(__file__).resolve().parents[4] / "tools" / "migration_support" / "primitives.py"
PRIMITIVES_SPEC = importlib.util.spec_from_file_location("migration_support_primitives", PRIMITIVES_PATH)
SHARED_PRIMITIVES = importlib.util.module_from_spec(PRIMITIVES_SPEC)
assert PRIMITIVES_SPEC.loader is not None
sys.modules[PRIMITIVES_SPEC.name] = SHARED_PRIMITIVES
PRIMITIVES_SPEC.loader.exec_module(SHARED_PRIMITIVES)


def make_skill(body: str, name: str = "example-skill") -> str:
    return textwrap.dedent(
        f"""\
        ---
        name: {name}
        description: Example skill.
        ---

        {body.strip()}
        """
    )


@contextlib.contextmanager
def temporary_repo(
    skill_packages: dict[str, dict[str, str]],
    *,
    command_files: dict[str, str] | None = None,
    settings_files: dict[str, str] | None = None,
    codex_skill_names: tuple[str, ...] = (),
    existing_hooks_json: str | None = None,
):
    with tempfile.TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        source_skills_dir = root / ".claude" / "skills"
        source_commands_dir = root / ".claude" / "commands"
        target_skills_dir = root / ".codex" / "skills"
        claude_agents_dir = root / ".claude" / "agents"
        codex_agents_dir = root / ".codex" / "agents"
        hooks_path = root / ".codex" / "hooks.json"

        source_skills_dir.mkdir(parents=True)
        source_commands_dir.mkdir(parents=True)
        target_skills_dir.mkdir(parents=True)
        claude_agents_dir.mkdir(parents=True)
        codex_agents_dir.mkdir(parents=True)

        for name, files in skill_packages.items():
            skill_dir = source_skills_dir / name
            skill_dir.mkdir(parents=True, exist_ok=True)
            for relative_path, content in files.items():
                file_path = skill_dir / relative_path
                file_path.parent.mkdir(parents=True, exist_ok=True)
                file_path.write_text(textwrap.dedent(content).lstrip(), encoding="utf-8")

        for relative_path, content in (command_files or {}).items():
            command_path = source_commands_dir / relative_path
            command_path.parent.mkdir(parents=True, exist_ok=True)
            command_path.write_text(textwrap.dedent(content).lstrip(), encoding="utf-8")

        for relative_path, content in (settings_files or {}).items():
            settings_path = root / ".claude" / relative_path
            settings_path.parent.mkdir(parents=True, exist_ok=True)
            settings_path.write_text(textwrap.dedent(content).lstrip(), encoding="utf-8")

        for name in codex_skill_names:
            codex_skill_dir = target_skills_dir / name
            codex_skill_dir.mkdir(parents=True, exist_ok=True)
            (codex_skill_dir / "SKILL.md").write_text("# Codex skill\n", encoding="utf-8")

        if existing_hooks_json is not None:
            hooks_path.parent.mkdir(parents=True, exist_ok=True)
            hooks_path.write_text(existing_hooks_json, encoding="utf-8")

        with contextlib.ExitStack() as stack:
            stack.enter_context(patch.object(MODULE, "REPO_ROOT", root))
            stack.enter_context(patch.object(MODULE, "SOURCE_SKILLS_DIR", source_skills_dir))
            stack.enter_context(patch.object(MODULE, "SOURCE_COMMANDS_DIR", source_commands_dir))
            stack.enter_context(patch.object(MODULE, "TARGET_SKILLS_DIR", target_skills_dir))
            stack.enter_context(patch.object(MODULE, "SOURCE_AGENTS_DIR", claude_agents_dir))
            stack.enter_context(patch.object(MODULE, "TARGET_AGENTS_DIR", codex_agents_dir))
            stack.enter_context(patch.object(MODULE, "TARGET_HOOKS_PATH", hooks_path))
            yield root


class SkillMigrationClassifierTests(unittest.TestCase):
    def test_web_primitives_use_current_codex_mappings_in_both_tables(self) -> None:
        text = "Call WebSearch first, then WebFetch for the source page.\n"

        expected = (
            "Call # CODEX: use web_search; cached by default, "
            "live via --search when freshness matters first, "
            "then # CODEX: no direct WebFetch primitive; use shell/curl "
            "or HTTP client with network access "
            "for the source page.\n"
        )
        self.assertEqual(MODULE.apply_primitive_mappings(text), expected)
        self.assertEqual(SHARED_PRIMITIVES.apply_primitive_mappings(text), expected)

    def test_webfetch_mapping_does_not_imply_direct_codex_primitive(self) -> None:
        replacements = dict(MODULE.PRIMITIVE_REPLACEMENTS)
        shared_replacements = dict(SHARED_PRIMITIVES.PRIMITIVE_REPLACEMENTS)

        self.assertIn("no direct WebFetch primitive", replacements["WebFetch"])
        self.assertEqual(replacements["WebFetch"], shared_replacements["WebFetch"])

    def test_web_mapping_table_lines_are_not_rewritten(self) -> None:
        text = "| `WebSearch` -> `search` | Use WebFetch after it |\n"

        self.assertEqual(MODULE.apply_primitive_mappings(text), text)
        self.assertEqual(SHARED_PRIMITIVES.apply_primitive_mappings(text), text)

    def test_redirected_skill_short_circuits_explicit_analysis(self) -> None:
        skill_packages = {
            "example-history-skill": {
                "SKILL.md": """\
                    ---
                    name: example-history-skill
                    description: "REDIRECTED to pattern-miner (mode:history)."
                    ---

                    # example-history-skill — REDIRECTED

                    **Replacement**: Use `pattern-miner` with `source:history` for commit history mining.
                """,
                "references/IMPLEMENTATION.md": """\
                    # Implementation

                    Task({
                      description: "legacy task",
                    })
                """,
            }
        }

        with temporary_repo(skill_packages):
            stdout = io.StringIO()
            with contextlib.redirect_stdout(stdout):
                result = MODULE.migrate_skill(
                    "example-history-skill",
                    dry_run=True,
                    analysis_only=True,
                )

        output = stdout.getvalue()
        self.assertEqual(result.status, "REDIRECTED")
        self.assertIn("example-history-skill: REDIRECTED", output)
        self.assertIn("replacement: Use `pattern-miner` with `source:history`", output)
        self.assertNotIn("inline Claude Task() site", output)

    def test_support_and_provenance_references_do_not_block(self) -> None:
        skill_packages = {
            "pattern-miner": {
                "SKILL.md": make_skill(
                    """
                    # Pattern Miner

                    ## Troubleshooting
                    | Problem | Fix |
                    |---------|-----|
                    | code search index missing | Rebuild: see `Skill('example-index-maintenance')` |
                    | Search syntax help | See `Skill('example-index-search')` |

                    ## Related Skills
                    | Skill | Relationship |
                    |-------|--------------|
                    | `knowledge-management` | Sibling — documentation lifecycle where mined patterns feed into |

                    ## Evolution History
                    | Date | Version | Change | Source |
                    |------|---------|--------|--------|
                    | <migration-history-date> | v1.0.0 | Merged from `example-analysis-skill` and `example-history-skill` | Consolidation |

                    ## Source Skills
                    - `example-analysis-skill`
                    - `example-history-skill`
                    """,
                    name="pattern-miner",
                )
            },
            "example-index-maintenance": {"SKILL.md": make_skill("# code search Maintenance", name="example-index-maintenance")},
            "example-index-search": {"SKILL.md": make_skill("# code search Search", name="example-index-search")},
            "knowledge-management": {
                "SKILL.md": make_skill("# Knowledge Management", name="knowledge-management")
            },
            "example-analysis-skill": {"SKILL.md": make_skill("# Redirect", name="example-analysis-skill")},
            "example-history-skill": {"SKILL.md": make_skill("# Redirect", name="example-history-skill")},
        }

        with temporary_repo(skill_packages):
            classification = MODULE.classify_skill(Path(MODULE.SOURCE_SKILLS_DIR) / "pattern-miner")

        self.assertEqual(classification.status, MODULE.STATUS_MECHANICAL_SAFE)
        self.assertEqual(classification.missing_skills, [])
        self.assertEqual(classification.ambiguous_references, [])

    def test_cross_reference_skill_table_is_treated_as_reference_only(self) -> None:
        skill_packages = {
            "hybrid-search": {
                "SKILL.md": make_skill(
                    """
                    ## Cross-References to Specialized Skills

                    | Concern | Skill |
                    |---------|-------|
                    | Embedding model selection (provider A vs provider B), conditional adapter pattern | `integrating-example-ai` |
                    | ExampleService fallback, `runExampleOperation()` | `integrating-example-ai` |
                    """,
                    name="hybrid-search",
                )
            },
            "integrating-example-ai": {
                "SKILL.md": make_skill("# Example AI Integration", name="integrating-example-ai")
            },
        }

        with temporary_repo(skill_packages):
            classification = MODULE.classify_skill(Path(MODULE.SOURCE_SKILLS_DIR) / "hybrid-search")

        self.assertEqual(classification.status, MODULE.STATUS_MECHANICAL_SAFE)
        self.assertEqual(classification.missing_skills, [])
        self.assertEqual(classification.ambiguous_references, [])

    def test_nested_cross_reference_subsections_are_treated_as_reference_only(self) -> None:
        skill_packages = {
            "dx-patterns": {
                "SKILL.md": make_skill(
                    """
                    ## Cross-References

                    ### Context Reading Before Edits
                    - Documented fully in: `legacy-example-workflow` skill + `ask` skill

                    ### Skill File Progressive Disclosure
                    - Documented fully in: `skill-building-guide` skill
                    """,
                    name="dx-patterns",
                )
            },
            "legacy-example-workflow": {
                "SKILL.md": make_skill("# Example MCP Workflow", name="legacy-example-workflow")
            },
            "ask": {"SKILL.md": make_skill("# Ask", name="ask")},
            "skill-building-guide": {
                "SKILL.md": make_skill("# Skill Building Guide", name="skill-building-guide")
            },
        }

        with temporary_repo(skill_packages):
            classification = MODULE.classify_skill(Path(MODULE.SOURCE_SKILLS_DIR) / "dx-patterns")

        self.assertEqual(classification.status, MODULE.STATUS_MECHANICAL_SAFE)
        self.assertEqual(classification.missing_skills, [])
        self.assertEqual(classification.ambiguous_references, [])

    def test_operational_skill_invocation_blocks_when_only_claude_skill_exists(self) -> None:
        skill_packages = {
            "main-skill": {
                "SKILL.md": make_skill(
                    """
                    ## Step 1

                    Use Skill('foo') before continuing with the migration.
                    """,
                    name="main-skill",
                )
            },
            "foo": {"SKILL.md": make_skill("# Foo", name="foo")},
        }

        with temporary_repo(skill_packages):
            classification = MODULE.classify_skill(Path(MODULE.SOURCE_SKILLS_DIR) / "main-skill")

        self.assertEqual(classification.status, MODULE.STATUS_BLOCKED)
        self.assertEqual(classification.missing_skills, ["foo"])

    def test_ambiguous_skill_reference_requires_manual_review(self) -> None:
        skill_packages = {
            "main-skill": {
                "SKILL.md": make_skill(
                    """
                    ## Advanced Cases

                    For complex remediation, `foo` may help if the baseline workflow stalls.
                    """,
                    name="main-skill",
                )
            },
            "foo": {"SKILL.md": make_skill("# Foo", name="foo")},
        }

        with temporary_repo(skill_packages):
            classification = MODULE.classify_skill(Path(MODULE.SOURCE_SKILLS_DIR) / "main-skill")

        self.assertEqual(classification.status, MODULE.STATUS_MANUAL_REVIEW_REQUIRED)
        self.assertEqual(classification.missing_skills, [])
        self.assertEqual(len(classification.ambiguous_references), 1)
        self.assertEqual(classification.ambiguous_references[0].token, "foo")
        self.assertTrue(
            any(finding.trigger == "AMBIGUOUS skill reference: foo" for finding in classification.findings)
        )

    def test_ambiguous_reference_with_codex_parity_does_not_gate_migration(self) -> None:
        skill_packages = {
            "main-skill": {
                "SKILL.md": make_skill(
                    """
                    ## Advanced Cases

                    For complex remediation, `foo` may help if the baseline workflow stalls.
                    """,
                    name="main-skill",
                )
            },
            "foo": {"SKILL.md": make_skill("# Foo", name="foo")},
        }

        with temporary_repo(skill_packages, codex_skill_names=("foo",)):
            classification = MODULE.classify_skill(Path(MODULE.SOURCE_SKILLS_DIR) / "main-skill")

        self.assertEqual(classification.status, MODULE.STATUS_MECHANICAL_SAFE)
        self.assertEqual(classification.ambiguous_references, [])

    def test_manual_review_required_does_not_write_output(self) -> None:
        skill_packages = {
            "main-skill": {
                "SKILL.md": make_skill(
                    """
                    ## Advanced Cases

                    For complex remediation, `foo` may help if the baseline workflow stalls.
                    """,
                    name="main-skill",
                )
            },
            "foo": {"SKILL.md": make_skill("# Foo", name="foo")},
        }

        with temporary_repo(skill_packages) as root:
            stdout = io.StringIO()
            with contextlib.redirect_stdout(stdout):
                result = MODULE.migrate_skill(
                    "main-skill",
                    dry_run=False,
                    analysis_only=False,
                )

            output = stdout.getvalue()
            self.assertEqual(result.status, MODULE.STATUS_MANUAL_REVIEW_REQUIRED)
            self.assertEqual(result.action, "manual-review-required")
            self.assertIn("manual review required", output)
            self.assertFalse((root / ".codex" / "skills" / "main-skill").exists())

    def test_analysis_only_json_includes_ambiguous_candidates(self) -> None:
        skill_packages = {
            "main-skill": {
                "SKILL.md": make_skill(
                    """
                    ## Advanced Cases

                    For complex remediation, `foo` may help if the baseline workflow stalls.
                    """,
                    name="main-skill",
                )
            },
            "foo": {"SKILL.md": make_skill("# Foo", name="foo")},
        }

        with temporary_repo(skill_packages):
            stdout = io.StringIO()
            original_argv = sys.argv
            try:
                sys.argv = [
                    "migrate_claude_workflows_to_codex.py",
                    "--analysis-only",
                    "--json",
                    "--skill",
                    "main-skill",
                ]
                with contextlib.redirect_stdout(stdout):
                    exit_code = MODULE.main()
            finally:
                sys.argv = original_argv

        payload = json.loads(stdout.getvalue())
        self.assertEqual(exit_code, 0)
        self.assertEqual(payload["status"], MODULE.STATUS_MANUAL_REVIEW_REQUIRED)
        self.assertEqual(
            payload["classification"]["ambiguous_references"][0]["token"],
            "foo",
        )


class RewriteSelfSkillPathsTests(unittest.TestCase):
    def test_rewrites_exact_self_skill_paths_but_not_sibling_skills(self) -> None:
        src = Path("/tmp/repo/.claude/skills/example-planning-workflow/SKILL.md")
        text = (
            "See [.](.codex/skills/example-planning-workflow/SKILL.md) and "
            "[review](.codex/skills/example-review-workflow/SKILL.md)."
        )

        rewritten = MODULE.rewrite_self_skill_paths(text, src)

        self.assertIn("[.](SKILL.md)", rewritten)
        self.assertIn(
            "[review](.codex/skills/example-review-workflow/SKILL.md)",
            rewritten,
        )

    def test_rewrites_nested_self_skill_paths_to_portable_relative_paths(self) -> None:
        src = Path("/tmp/repo/.claude/skills/example-planning-workflow/references/example-review-prompts.md")
        text = "Contract: .codex/skills/example-planning-workflow/references/example-review-context.md"

        rewritten = MODULE.rewrite_self_skill_paths(text, src)

        self.assertEqual(rewritten, "Contract: example-review-context.md")


class CommandConversionTests(unittest.TestCase):
    def test_converts_simple_claude_command_to_command_skill(self) -> None:
        with temporary_repo({}, command_files={"deploy.md": "Run deployment\n"}) as root:
            report = MODULE.migrate_project_surfaces(dry_run=False, analysis_only=False)

            output = root / ".codex" / "skills" / "command-deploy" / "SKILL.md"
            text = output.read_text(encoding="utf-8")

        self.assertEqual(report.commands[0].target_skill, "command-deploy")
        self.assertEqual(report.commands[0].status, "manual-review-required")
        self.assertEqual(MODULE._surface_summary(report)["manual_review_items"], 1)
        self.assertIn("name: command-deploy", text)
        self.assertIn("## Command Template", text)
        self.assertIn("## MANUAL MIGRATION REQUIRED", text)

    def test_converts_nested_command_with_stable_name(self) -> None:
        with temporary_repo({}, command_files={"db/migrate.md": "Run db migration\n"}) as root:
            MODULE.migrate_project_surfaces(dry_run=False, analysis_only=False)

            output = root / ".codex" / "skills" / "command-db-migrate" / "SKILL.md"
            self.assertTrue(output.exists())

    def test_command_uses_frontmatter_description(self) -> None:
        with temporary_repo(
            {},
            command_files={
                "release.md": """\
                    ---
                    description: Ship a release.
                    ---

                    Run release.
                """
            },
        ) as root:
            MODULE.migrate_project_surfaces(dry_run=False, analysis_only=False)
            text = (root / ".codex" / "skills" / "command-release" / "SKILL.md").read_text(
                encoding="utf-8"
            )

        self.assertIn("description: Ship a release.", text)

    def test_existing_user_command_skill_blocks_live_write(self) -> None:
        with temporary_repo(
            {},
            command_files={"deploy.md": "Run deployment\n"},
            codex_skill_names=("command-deploy",),
        ) as root:
            output = root / ".codex" / "skills" / "command-deploy" / "SKILL.md"
            before = output.read_text(encoding="utf-8")
            report = MODULE.migrate_project_surfaces(dry_run=False, analysis_only=False)
            after = output.read_text(encoding="utf-8")

        self.assertEqual(before, "# Codex skill\n")
        self.assertEqual(after, before)
        self.assertEqual(report.commands[0].status, "target-collision")
        self.assertIn("merge manually", "\n".join(report.commands[0].manual_review_reasons))

    def test_command_placeholder_caveats(self) -> None:
        with temporary_repo({}, command_files={"test.md": "Run $ARGUMENTS then inspect $1\n"}):
            report = MODULE.migrate_project_surfaces(dry_run=True, analysis_only=False)

        reasons = "\n".join(report.commands[0].manual_review_reasons)
        self.assertIn("argument placeholders", reasons)
        self.assertIn("positional placeholders", reasons)
        self.assertEqual(report.commands[0].status, "manual-review-required")

    def test_command_template_shell_file_and_frontmatter_caveats(self) -> None:
        with temporary_repo(
            {},
            command_files={
                "service.md": """\
                    ---
                    description: Service command.
                    allowed-tools: Bash
                    ---

                    Check {{service}}, run !`git status`, and read @docs/runbook.md plus @path.
                """
            },
        ):
            report = MODULE.migrate_project_surfaces(dry_run=True, analysis_only=False)

        reasons = "\n".join(report.commands[0].manual_review_reasons)
        self.assertIn("template variables", reasons)
        self.assertIn("shell interpolation", reasons)
        self.assertIn("@ files", reasons)
        self.assertIn("allowed-tools", reasons)

    def test_command_slug_collision_uses_hash_suffix(self) -> None:
        with temporary_repo(
            {},
            command_files={
                "foo_bar.md": "Run A\n",
                "foo/bar.md": "Run B\n",
            },
        ):
            report = MODULE.migrate_project_surfaces(dry_run=True, analysis_only=False)

        names = sorted(command.target_skill for command in report.commands)
        self.assertEqual(len(names), 2)
        self.assertTrue(all(name.startswith("command-foo-bar-") for name in names))
        self.assertTrue(all(command.collision_suffix_applied for command in report.commands))


class HookConversionTests(unittest.TestCase):
    def test_converts_supported_stop_hook_to_codex_hooks_json(self) -> None:
        with temporary_repo(
            {},
            settings_files={
                "settings.json": json.dumps(
                    {"hooks": {"Stop": [{"hooks": [{"type": "command", "command": "npm test"}]}]}}
                )
            },
        ) as root:
            report = MODULE.migrate_project_surfaces(dry_run=False, analysis_only=False)
            payload = json.loads((root / ".codex" / "hooks.json").read_text(encoding="utf-8"))

        self.assertEqual(payload["_generated_by"], MODULE.GENERATED_HOOKS_MARKER)
        self.assertEqual(payload["hooks"]["Stop"][0]["hooks"][0]["command"], "npm test")
        self.assertEqual(report.hooks[0].status, "converted-hook-review-required")

    def test_converts_pretooluse_matcher(self) -> None:
        with temporary_repo(
            {},
            settings_files={
                "settings.json": json.dumps(
                    {
                        "hooks": {
                            "PreToolUse": [
                                {
                                    "matcher": "Bash",
                                    "hooks": [{"command": "npm run lint", "timeoutSec": 30}],
                                }
                            ]
                        }
                    }
                )
            },
        ) as root:
            MODULE.migrate_project_surfaces(dry_run=False, analysis_only=False)
            payload = json.loads((root / ".codex" / "hooks.json").read_text(encoding="utf-8"))

        self.assertEqual(payload["hooks"]["PreToolUse"][0]["matcher"], "Bash")
        self.assertEqual(payload["hooks"]["PreToolUse"][0]["hooks"][0]["timeout"], 30)

    def test_omits_stop_matcher_and_reports_review(self) -> None:
        with temporary_repo(
            {},
            settings_files={
                "settings.json": json.dumps(
                    {
                        "hooks": {
                            "Stop": [
                                {"matcher": "Bash", "hooks": [{"command": "npm test"}]}
                            ]
                        }
                    }
                )
            },
        ) as root:
            report = MODULE.migrate_project_surfaces(dry_run=False, analysis_only=False)
            payload = json.loads((root / ".codex" / "hooks.json").read_text(encoding="utf-8"))

        self.assertNotIn("matcher", payload["hooks"]["Stop"][0])
        self.assertIn("matcher omitted", "\n".join(report.hooks[0].manual_review_reasons))

    def test_timeout_precedence_reports_when_both_timeout_fields_exist(self) -> None:
        with temporary_repo(
            {},
            settings_files={
                "settings.json": json.dumps(
                    {
                        "hooks": {
                            "PostToolUse": [
                                {
                                    "matcher": "Bash",
                                    "hooks": [{"command": "npm test", "timeout": 10, "timeoutSec": 30}],
                                }
                            ]
                        }
                    }
                )
            },
        ) as root:
            report = MODULE.migrate_project_surfaces(dry_run=False, analysis_only=False)
            payload = json.loads((root / ".codex" / "hooks.json").read_text(encoding="utf-8"))

        self.assertEqual(payload["hooks"]["PostToolUse"][0]["hooks"][0]["timeout"], 10)
        self.assertIn("timeoutSec", "\n".join(report.hooks[0].manual_review_reasons))

    def test_non_command_and_async_hooks_are_skipped_and_reported(self) -> None:
        with temporary_repo(
            {},
            settings_files={
                "settings.json": json.dumps(
                    {
                        "hooks": {
                            "Stop": [
                                {
                                    "hooks": [
                                        {"type": "prompt", "command": "mutate prompt"},
                                        {"type": "command", "command": "npm test", "async": True},
                                    ]
                                }
                            ]
                        }
                    }
                )
            },
        ):
            report = MODULE.migrate_project_surfaces(dry_run=True, analysis_only=False)

        self.assertEqual(report.hooks, [])
        self.assertEqual(len(report.unsupported_hooks), 2)

    def test_generated_hooks_json_refreshes_on_second_live_batch_run(self) -> None:
        settings = {
            "settings.json": json.dumps(
                {"hooks": {"Stop": [{"hooks": [{"command": "npm test"}]}]}}
            )
        }
        with temporary_repo({}, settings_files=settings) as root:
            first_report = MODULE.migrate_project_surfaces(dry_run=False, analysis_only=False)
            second_report = MODULE.migrate_project_surfaces(dry_run=False, analysis_only=False)
            payload = json.loads((root / ".codex" / "hooks.json").read_text(encoding="utf-8"))

        self.assertEqual(payload["_generated_by"], MODULE.GENERATED_HOOKS_MARKER)
        self.assertTrue(first_report.generated_artifacts)
        self.assertFalse(
            any(item["status"] == "target-collision" for item in second_report.unsupported_hooks)
        )
        self.assertEqual(second_report.generated_artifacts, [".codex/hooks.json"])

    def test_invalid_settings_json_reports_without_writing(self) -> None:
        with temporary_repo({}, settings_files={"settings.json": "{not json"}) as root:
            report = MODULE.migrate_project_surfaces(dry_run=False, analysis_only=False)

        self.assertFalse((root / ".codex" / "hooks.json").exists())
        self.assertEqual(report.unsupported_hooks[0]["status"], "invalid-source-json")

    def test_existing_user_hooks_json_blocks_live_write(self) -> None:
        with temporary_repo(
            {},
            settings_files={
                "settings.json": json.dumps(
                    {"hooks": {"Stop": [{"hooks": [{"command": "npm test"}]}]}}
                )
            },
            existing_hooks_json='{"hooks": {}}\n',
        ) as root:
            report = MODULE.migrate_project_surfaces(dry_run=False, analysis_only=False)
            text = (root / ".codex" / "hooks.json").read_text(encoding="utf-8")

        self.assertEqual(text, '{"hooks": {}}\n')
        self.assertNotIn(MODULE.GENERATED_HOOKS_MARKER, text)
        self.assertTrue(any(item["status"] == "target-collision" for item in report.unsupported_hooks))


class ProjectSurfaceFlowTests(unittest.TestCase):
    def test_single_skill_mode_does_not_convert_commands_or_hooks(self) -> None:
        skill_packages = {"example-skill": {"SKILL.md": make_skill("# Example")}}
        with temporary_repo(
            skill_packages,
            command_files={"deploy.md": "Deploy\n"},
            settings_files={
                "settings.json": json.dumps(
                    {"hooks": {"Stop": [{"hooks": [{"command": "npm test"}]}]}}
                )
            },
        ) as root:
            MODULE.migrate_skill("example-skill", dry_run=False, analysis_only=False, emit_text=False)

        self.assertFalse((root / ".codex" / "skills" / "command-deploy").exists())
        self.assertFalse((root / ".codex" / "hooks.json").exists())

    def test_analysis_only_reports_commands_and_hooks_without_writing(self) -> None:
        with temporary_repo(
            {},
            command_files={"deploy.md": "Deploy\n"},
            settings_files={
                "settings.json": json.dumps(
                    {"hooks": {"Stop": [{"hooks": [{"command": "npm test"}]}]}}
                )
            },
        ) as root:
            stdout = io.StringIO()
            original_argv = sys.argv
            try:
                sys.argv = [
                    "migrate_claude_workflows_to_codex.py",
                    "--analysis-only",
                    "--json",
                ]
                with contextlib.redirect_stdout(stdout):
                    exit_code = MODULE.main()
            finally:
                sys.argv = original_argv

            payload = json.loads(stdout.getvalue())

        self.assertEqual(exit_code, 0)
        self.assertEqual(payload["summary"]["commands_discovered"], 1)
        self.assertEqual(payload["summary"]["manual_review_items"], 2)
        self.assertEqual(payload["summary"]["hook_entries_generated"], 1)
        self.assertFalse((root / ".codex" / "skills" / "command-deploy").exists())
        self.assertFalse((root / ".codex" / "hooks.json").exists())

    def test_dry_run_reports_commands_and_hooks_without_writing(self) -> None:
        with temporary_repo(
            {},
            command_files={"deploy.md": "Deploy\n"},
            settings_files={
                "settings.json": json.dumps(
                    {"hooks": {"Stop": [{"hooks": [{"command": "npm test"}]}]}}
                )
            },
        ) as root:
            stdout = io.StringIO()
            original_argv = sys.argv
            try:
                sys.argv = ["migrate_claude_workflows_to_codex.py", "--dry-run", "--json"]
                with contextlib.redirect_stdout(stdout):
                    MODULE.main()
            finally:
                sys.argv = original_argv

        self.assertFalse((root / ".codex" / "skills" / "command-deploy").exists())
        self.assertFalse((root / ".codex" / "hooks.json").exists())

    def test_live_batch_generates_outputs(self) -> None:
        with temporary_repo(
            {},
            command_files={"deploy.md": "Deploy\n"},
            settings_files={
                "settings.json": json.dumps(
                    {"hooks": {"Stop": [{"hooks": [{"command": "npm test"}]}]}}
                )
            },
        ) as root:
            stdout = io.StringIO()
            original_argv = sys.argv
            try:
                sys.argv = ["migrate_claude_workflows_to_codex.py", "--json"]
                with contextlib.redirect_stdout(stdout):
                    MODULE.main()
            finally:
                sys.argv = original_argv

            self.assertTrue(
                (root / ".codex" / "skills" / "command-deploy" / "SKILL.md").exists()
            )
            self.assertTrue((root / ".codex" / "hooks.json").exists())


if __name__ == "__main__":
    unittest.main()
